# https://docs.ansible.com/ansible/latest/network/user_guide/platform_ios.html
---
ansible_connection: ansible.netcommon.network_cli
ansible_network_os: cisco.ios.ios
ansible_user: iosuser
ansible_become: true
ansible_become_method: enable

...
