# https://github.com/marketplace/actions/run-ansible-lint
---
name: ansible-lint
on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]
env:
  ANSIBLE_GALAXY_SERVER_AUTOMATION_HUB_TOKEN: ${{ secrets.automation_hub_token }}
jobs:
  build:
    name: Ansible Lint  # Naming the build is important to use it as a status check
    runs-on: ubuntu-latest
    steps:
      # this action implicitly calls actions/checkout
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v6.18.0  # match tag to .pre-commit-config.yaml

...
